# kind (Kubernetes in Docker) cluster configuration
# This creates a local Kubernetes cluster for development and testing

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

# Cluster name
name: taskmanager-cluster

# Kubernetes version (optional)
# image: kindest/node:v1.28.0

# Cluster nodes configuration
nodes:
# Control plane node
- role: control-plane
  # Port mappings for accessing services
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # HTTP ingress
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # HTTPS ingress
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # NodePort range
  - containerPort: 30080
    hostPort: 30080
    protocol: TCP

# Worker nodes (optional - add more for multi-node testing)
- role: worker
- role: worker

# Networking configuration
networking:
  # Disable default CNI to install custom one
  disableDefaultCNI: false
  # Pod subnet
  podSubnet: "10.244.0.0/16"
  # Service subnet
  serviceSubnet: "10.96.0.0/12"

# Feature gates (optional)
featureGates:
  # Enable feature gates if needed
  # "SomeFeature": true
